server:
  port: 8081
spring:
  application:
    name: zinfos-user
  main:
    allow-bean-definition-overriding: true
#  redis:
#    database: 1
#    host: 39.108.213.94
#    port: 6379
#    timeout: 3000ms
#    password: zhouwei1990
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms
#        max-active: 8
#    testOnBorrow: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/springboot_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource