server:
  port: 8081
spring:
  application:
    name: zinfos-user
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:80/eureka/